from _typeshed import Incomplete

class Settings:
    def __init__(self) -> None: ...
    def set(self, name, value) -> None: ...
    def get(self, name, default: Incomplete | None = ...): ...
    def reset_to_defaults(self) -> None: ...

settings: Incomplete
get_setting: Incomplete
set_setting: Incomplete
reset_to_defaults_settings: Incomplete
