class LanguageCodeError(Exception): ...
class ImproperlyConfigured(Exception): ...
class LanguagePackNotFound(Exception): ...
class LanguageDetectionError(Exception): ...
class InvalidRegistryItemType(ValueError): ...
