from _typeshed import Incomplete

def tags(*t): ...
def between(a, b, inclusive_min: bool = ..., inclusive_max: bool = ...): ...
def equal(n): ...
def lt(n): ...
def le(n): ...
def gt(n): ...
def ge(n): ...
def geo(lat, lon, radius, unit: str = ...): ...

class Value:
    @property
    def combinable(self): ...
    @staticmethod
    def make_value(v): ...
    def to_string(self) -> None: ...

class RangeValue(Value):
    combinable: bool
    range: Incomplete
    inclusive_min: Incomplete
    inclusive_max: Incomplete
    def __init__(self, a, b, inclusive_min: bool = ..., inclusive_max: bool = ...) -> None: ...
    def to_string(self): ...

class ScalarValue(Value):
    combinable: bool
    v: Incomplete
    def __init__(self, v) -> None: ...
    def to_string(self): ...

class TagValue(Value):
    combinable: bool
    tags: Incomplete
    def __init__(self, *tags) -> None: ...
    def to_string(self): ...

class GeoValue(Value):
    lon: Incomplete
    lat: Incomplete
    radius: Incomplete
    unit: Incomplete
    def __init__(self, lon, lat, radius, unit: str = ...) -> None: ...
    def to_string(self): ...

class Node:
    params: Incomplete
    def __init__(self, *children, **kwparams) -> None: ...
    def join_fields(self, key, vals): ...
    @classmethod
    def to_node(cls, obj): ...
    @property
    def JOINSTR(self) -> None: ...
    def to_string(self, with_parens: Incomplete | None = ...): ...

class BaseNode(Node):
    s: Incomplete
    def __init__(self, s) -> None: ...
    def to_string(self, with_parens: Incomplete | None = ...): ...

class IntersectNode(Node):
    JOINSTR: str

class UnionNode(Node):
    JOINSTR: str

class DisjunctNode(IntersectNode):
    def to_string(self, with_parens: Incomplete | None = ...): ...

class DistjunctUnion(DisjunctNode):
    JOINSTR: str

class OptionalNode(IntersectNode):
    def to_string(self, with_parens: Incomplete | None = ...): ...

def intersect(*args, **kwargs): ...
def union(*args, **kwargs): ...
def disjunct(*args, **kwargs): ...
def disjunct_union(*args, **kwargs): ...
def querystring(*args, **kwargs): ...
