import unittest
from _typeshed import Incomplete

class TransliterateTest(unittest.TestCase):
    latin_text: Incomplete
    armenian_text: Incomplete
    cyrillic_text: Incomplete
    ukrainian_cyrillic_text: Incomplete
    bulgarian_cyrillic_text: Incomplete
    georgian_text: Incomplete
    greek_text: Incomplete
    hebrew_text: Incomplete
    mongolian_cyrillic_text: Incomplete
    serbian_cyrillic_text: Incomplete
    pangram_serbian_cyrillic_text: Incomplete
    pangram_serbian_latin_text: Incomplete
    def setUp(self) -> None: ...
    def test_01_get_available_language_codes(self): ...
    def test_02_translit_latin_to_armenian(self): ...
    def test_03_translit_latin_to_georgian(self): ...
    def test_04_translit_latin_to_greek(self): ...
    def test_06_translit_latin_to_cyrillic(self): ...
    def test_06_translit_latin_to_ukrainian_cyrillic(self): ...
    def test_06_translit_latin_to_bulgarian_cyrillic(self): ...
    def test_06_translit_latin_to_mongolian_cyrillic(self): ...
    def test_06_translit_latin_to_serbian_cyrillic(self): ...
    def test_07_translit_armenian_to_latin(self): ...
    def test_08_translit_georgian_to_latin(self): ...
    def test_09_translit_greek_to_latin(self): ...
    def test_11_translit_cyrillic_to_latin(self): ...
    def test_11_translit_ukrainian_cyrillic_to_latin(self): ...
    def test_11_translit_bulgarian_cyrillic_to_latin(self): ...
    def test_11_translit_mongolian_cyrillic_to_latin(self): ...
    def test_11_translit_serbian_cyrillic_to_latin(self): ...
    def test_12_function_decorator(self): ...
    def test_13_method_decorator(self): ...
    def test_14_function_decorator(self): ...
    def test_15_register_custom_language_pack(self): ...
    def test_16_translipsum_generator_armenian(self): ...
    def test_17_translipsum_generator_georgian(self): ...
    def test_18_translipsum_generator_greek(self): ...
    def test_20_translipsum_generator_cyrillic(self): ...
    def test_20_translipsum_generator_ukrainian_cyrillic(self): ...
    def test_20_translipsum_generator_bulgarian_cyrillic(self): ...
    def test_20_translipsum_generator_mongolian_cyrillic(self): ...
    def test_20_translipsum_generator_serbian_cyrillic(self): ...
    def test_21_language_detection_armenian(self): ...
    def test_22_language_detection_georgian(self): ...
    def test_23_language_detection_greek(self): ...
    def test_25_language_detection_cyrillic(self): ...
    def test_25_false_language_detection_cyrillic(self): ...
    def test_26_slugify_armenian(self): ...
    def test_27_slugify_georgian(self): ...
    def test_28_slugify_greek(self): ...
    def test_30_slugify_cyrillic(self): ...
    def test_30_slugify_ukrainian_cyrillic(self): ...
    def test_30_slugify_bulgarian_cyrillic(self): ...
    def test_30_slugify_mongolian_cyrillic(self): ...
    def test_30_slugify_serbian_cyrillic(self): ...
    def test_31b_get_translit_function(self) -> None: ...
    def test_31_override_settings(self): ...
    def test_32_auto_translit_reversed(self): ...
    def test_33_register_unregister(self) -> None: ...
    def test_35_translit_serbian_latin_to_serbian_cyrillic(self): ...
    def test_35_translit_serbian_cyrillic_to_serbian_latin(self): ...
