from ...orm.decl_api import DeclarativeMeta as DeclarativeMeta, declared_attr as declared_attr
from .extensions import AbstractConcreteBase as AbstractConcreteBase, ConcreteBase as ConcreteBase, DeferredReflection as DeferredReflection

def declarative_base(*arg, **kw): ...
def as_declarative(*arg, **kw): ...
def has_inherited_table(*arg, **kw): ...
def synonym_for(*arg, **kw): ...

# Names in __all__ with no definition:
#   instrument_declarative
