"""empty message

Revision ID: 0d7825fba0af
Revises: 264f044566de
Create Date: 2023-12-07 12:48:11.180273

"""
# Standard Library
from typing import (
    Sequence,
    Union,
)

# Third Party Stuff
import sqlalchemy as sa

# My Stuff
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d7825fba0af"
down_revision: Union[str, None] = "264f044566de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "race_classes",
        sa.Column(
            "a_category_percentage", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("race_classes", "a_category_percentage")
    # ### end Alembic commands ###
