"""empty message

Revision ID: 0ee92dfc8941
Revises: 95cf7d885d75
Create Date: 2023-11-29 02:09:59.933078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee92dfc8941'
down_revision: Union[str, None] = '95cf7d885d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('athlete_start_uniq', 'athlete_categories', ['start', 'athlete_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('athlete_start_uniq', 'athlete_categories', type_='unique')
    # ### end Alembic commands ###
