"""empty message

Revision ID: 24a4b6c82df6
Revises: 0d7825fba0af
Create Date: 2023-12-07 13:34:08.031350

"""
# Standard Library
from typing import (
    Sequence,
    Union,
)

# Third Party Stuff
import sqlalchemy as sa

# My Stuff
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24a4b6c82df6"
down_revision: Union[str, None] = "0d7825fba0af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("athlete_start_uniq", "athlete_categories", type_="unique")
    op.create_unique_constraint("athlete_uniq", "athlete_categories", ["athlete_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("athlete_uniq", "athlete_categories", type_="unique")
    op.create_unique_constraint(
        "athlete_start_uniq", "athlete_categories", ["start", "athlete_id"]
    )
    # ### end Alembic commands ###
