"""empty message

Revision ID: 264f044566de
Revises: 0ee92dfc8941
Create Date: 2023-11-29 12:32:08.821537

"""
# Standard Library
from typing import (
    Sequence,
    Union,
)

# Third Party Stuff
import sqlalchemy as sa

# My Stuff
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "264f044566de"
down_revision: Union[str, None] = "0ee92dfc8941"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sex",
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sex", "enabled")
    # ### end Alembic commands ###
