"""empty message

Revision ID: 55780f7cfca0
Revises: 3e8b33d501d1
Create Date: 2023-11-25 02:15:42.564704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55780f7cfca0'
down_revision: Union[str, None] = '3e8b33d501d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('athlete_race_uniq', 'race_results', ['athlete_id', 'race_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('athlete_race_uniq', 'race_results', type_='unique')
    # ### end Alembic commands ###
