"""empty message

Revision ID: 89d8f1e7eacf
Revises: ee0ce3b4f685
Create Date: 2023-11-25 11:42:58.553363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d8f1e7eacf'
down_revision: Union[str, None] = 'ee0ce3b4f685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replace_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('replace_name', sa.String(length=90), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replace_name')
    # ### end Alembic commands ###
