"""empty message

Revision ID: 9d2815a9ce58
Revises: 93a7eacdcb81
Create Date: 2023-11-25 11:50:47.110847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2815a9ce58'
down_revision: Union[str, None] = '93a7eacdcb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'replace_name', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replace_name', type_='unique')
    # ### end Alembic commands ###
