"""empty message

Revision ID: bfc6f545fce7
Revises: 9d2815a9ce58
Create Date: 2023-11-25 20:13:32.648442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc6f545fce7'
down_revision: Union[str, None] = '9d2815a9ce58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_for_place', sa.Column('sex_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'points_for_place', 'sex', ['sex_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('race_results_race_id_fkey', 'race_results', type_='foreignkey')
    op.create_foreign_key(None, 'race_results', 'races', ['race_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race_results', type_='foreignkey')
    op.create_foreign_key('race_results_race_id_fkey', 'race_results', 'races', ['race_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'points_for_place', type_='foreignkey')
    op.drop_column('points_for_place', 'sex_id')
    # ### end Alembic commands ###
