from . import config as config
from ..util import has_compiled_ext as has_compiled_ext
from .util import gc_collect as gc_collect
from _typeshed import Incomplete
from collections.abc import Generator

class ProfileStatsFile:
    force_write: Incomplete
    write: Incomplete
    fname: Incomplete
    short_fname: Incomplete
    data: Incomplete
    dump: Incomplete
    sort: Incomplete
    def __init__(self, filename, sort: str = ..., dump: Incomplete | None = ...) -> None: ...
    @property
    def platform_key(self): ...
    def has_stats(self): ...
    def result(self, callcount): ...
    def reset_count(self) -> None: ...
    def replace(self, callcount) -> None: ...

def function_call_count(variance: float = ..., times: int = ..., warmup: int = ...): ...
def count_functions(variance: float = ...) -> Generator[None, None, None]: ...
