from .. import schema
from _typeshed import Incomplete

def Table(*args, **kw) -> schema.Table: ...
def Column(*args, **kw): ...

class eq_type_affinity:
    target: Incomplete
    def __init__(self, target) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class eq_compile_type:
    target: Incomplete
    def __init__(self, target) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class eq_clause_element:
    target: Incomplete
    def __init__(self, target) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
