from transliterate.contrib.apps.translipsum.utils import Generator

class TranslipsumGenerator(Generator):
    def __init__(self, language_code, reversed: bool = ..., *args, **kwargs) -> None: ...
    def generate_sentence(self, *args, **kwargs): ...
    def generate_paragraph(self, *args, **kwargs): ...
