class Generator:
    def __init__(self, *args, **kwargs) -> None: ...
    def generate_word(self): ...
    def generate_sentence(self): ...
    def generate_paragraph(self, num_sentences: int = ...): ...
