from .. import exc as exc, util as util
from ..util._has_cy import HAS_CYEXTENSION as HAS_CYEXTENSION
from ..util.typing import Protocol as Protocol
from typing import Any, Callable

def connection_memoize(key: str) -> Callable[[_C], _C]: ...

class _TConsSubject(Protocol): ...

class TransactionalContext:
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> TransactionalContext: ...
    def __exit__(self, type_: Any, value: Any, traceback: Any) -> None: ...
