from _typeshed import Incomplete
from telebot import types as types, util as util

format_header_param: Incomplete
logger: Incomplete
proxy: Incomplete
session: Incomplete
API_URL: Incomplete
FILE_URL: Incomplete
CONNECT_TIMEOUT: int
READ_TIMEOUT: int
LONG_POLLING_TIMEOUT: int
SESSION_TIME_TO_LIVE: int
RETRY_ON_ERROR: bool
RETRY_TIMEOUT: int
MAX_RETRIES: int
RETRY_ENGINE: int
CUSTOM_SERIALIZER: Incomplete
CUSTOM_REQUEST_SENDER: Incomplete
ENABLE_MIDDLEWARE: bool

def get_me(token): ...
def log_out(token): ...
def close(token): ...
def get_file(token, file_id): ...
def get_file_url(token, file_id): ...
def download_file(token, file_path): ...
def send_message(token, chat_id, text, disable_web_page_preview: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., parse_mode: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., entities: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def set_webhook(token, url: Incomplete | None = ..., certificate: Incomplete | None = ..., max_connections: Incomplete | None = ..., allowed_updates: Incomplete | None = ..., ip_address: Incomplete | None = ..., drop_pending_updates: Incomplete | None = ..., timeout: Incomplete | None = ..., secret_token: Incomplete | None = ...): ...
def delete_webhook(token, drop_pending_updates: Incomplete | None = ..., timeout: Incomplete | None = ...): ...
def get_webhook_info(token, timeout: Incomplete | None = ...): ...
def get_updates(token, offset: Incomplete | None = ..., limit: Incomplete | None = ..., timeout: Incomplete | None = ..., allowed_updates: Incomplete | None = ..., long_polling_timeout: Incomplete | None = ...): ...
def get_user_profile_photos(token, user_id, offset: Incomplete | None = ..., limit: Incomplete | None = ...): ...
def get_chat(token, chat_id): ...
def leave_chat(token, chat_id): ...
def get_chat_administrators(token, chat_id): ...
def get_chat_member_count(token, chat_id): ...
def set_sticker_set_thumbnail(token, name, user_id, thumbnail): ...
def set_chat_sticker_set(token, chat_id, sticker_set_name): ...
def delete_chat_sticker_set(token, chat_id): ...
def get_chat_member(token, chat_id, user_id): ...
def forward_message(token, chat_id, from_chat_id, message_id, disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def copy_message(token, chat_id, from_chat_id, message_id, caption: Incomplete | None = ..., parse_mode: Incomplete | None = ..., caption_entities: Incomplete | None = ..., disable_notification: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_dice(token, chat_id, emoji: Incomplete | None = ..., disable_notification: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_photo(token, chat_id, photo, caption: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., parse_mode: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., caption_entities: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ..., has_spoiler: Incomplete | None = ...): ...
def send_media_group(token, chat_id, media, disable_notification: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., timeout: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_location(token, chat_id, latitude, longitude, live_period: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., horizontal_accuracy: Incomplete | None = ..., heading: Incomplete | None = ..., proximity_alert_radius: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def edit_message_live_location(token, latitude, longitude, chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ..., horizontal_accuracy: Incomplete | None = ..., heading: Incomplete | None = ..., proximity_alert_radius: Incomplete | None = ...): ...
def stop_message_live_location(token, chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ...): ...
def send_venue(token, chat_id, latitude, longitude, title, address, foursquare_id: Incomplete | None = ..., foursquare_type: Incomplete | None = ..., disable_notification: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., google_place_id: Incomplete | None = ..., google_place_type: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_contact(token, chat_id, phone_number, first_name, last_name: Incomplete | None = ..., vcard: Incomplete | None = ..., disable_notification: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_chat_action(token, chat_id, action, timeout: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_video(token, chat_id, data, duration: Incomplete | None = ..., caption: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., parse_mode: Incomplete | None = ..., supports_streaming: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., thumbnail: Incomplete | None = ..., width: Incomplete | None = ..., height: Incomplete | None = ..., caption_entities: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ..., has_spoiler: Incomplete | None = ...): ...
def send_animation(token, chat_id, data, duration: Incomplete | None = ..., caption: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., parse_mode: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., thumbnail: Incomplete | None = ..., caption_entities: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., width: Incomplete | None = ..., height: Incomplete | None = ..., message_thread_id: Incomplete | None = ..., has_spoiler: Incomplete | None = ...): ...
def send_voice(token, chat_id, voice, caption: Incomplete | None = ..., duration: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., parse_mode: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., caption_entities: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_video_note(token, chat_id, data, duration: Incomplete | None = ..., length: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., thumbnail: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_audio(token, chat_id, audio, caption: Incomplete | None = ..., duration: Incomplete | None = ..., performer: Incomplete | None = ..., title: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., parse_mode: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., thumbnail: Incomplete | None = ..., caption_entities: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def send_data(token, chat_id, data, data_type, reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., parse_mode: Incomplete | None = ..., disable_notification: Incomplete | None = ..., timeout: Incomplete | None = ..., caption: Incomplete | None = ..., thumbnail: Incomplete | None = ..., caption_entities: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., disable_content_type_detection: Incomplete | None = ..., visible_file_name: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ..., emoji: Incomplete | None = ...): ...
def get_method_by_type(data_type): ...
def ban_chat_member(token, chat_id, user_id, until_date: Incomplete | None = ..., revoke_messages: Incomplete | None = ...): ...
def unban_chat_member(token, chat_id, user_id, only_if_banned): ...
def restrict_chat_member(token, chat_id, user_id, permissions, until_date: Incomplete | None = ..., use_independent_chat_permissions: Incomplete | None = ...): ...
def promote_chat_member(token, chat_id, user_id, can_change_info: Incomplete | None = ..., can_post_messages: Incomplete | None = ..., can_edit_messages: Incomplete | None = ..., can_delete_messages: Incomplete | None = ..., can_invite_users: Incomplete | None = ..., can_restrict_members: Incomplete | None = ..., can_pin_messages: Incomplete | None = ..., can_promote_members: Incomplete | None = ..., is_anonymous: Incomplete | None = ..., can_manage_chat: Incomplete | None = ..., can_manage_video_chats: Incomplete | None = ..., can_manage_topics: Incomplete | None = ..., can_post_stories: Incomplete | None = ..., can_edit_stories: Incomplete | None = ..., can_delete_stories: Incomplete | None = ...): ...
def set_chat_administrator_custom_title(token, chat_id, user_id, custom_title): ...
def ban_chat_sender_chat(token, chat_id, sender_chat_id): ...
def unban_chat_sender_chat(token, chat_id, sender_chat_id): ...
def set_chat_permissions(token, chat_id, permissions, use_independent_chat_permissions: Incomplete | None = ...): ...
def create_chat_invite_link(token, chat_id, name, expire_date, member_limit, creates_join_request): ...
def edit_chat_invite_link(token, chat_id, invite_link, name, expire_date, member_limit, creates_join_request): ...
def revoke_chat_invite_link(token, chat_id, invite_link): ...
def export_chat_invite_link(token, chat_id): ...
def approve_chat_join_request(token, chat_id, user_id): ...
def decline_chat_join_request(token, chat_id, user_id): ...
def set_chat_photo(token, chat_id, photo): ...
def delete_chat_photo(token, chat_id): ...
def set_chat_title(token, chat_id, title): ...
def set_my_description(token, description: Incomplete | None = ..., language_code: Incomplete | None = ...): ...
def get_my_description(token, language_code: Incomplete | None = ...): ...
def set_my_short_description(token, short_description: Incomplete | None = ..., language_code: Incomplete | None = ...): ...
def get_my_short_description(token, language_code: Incomplete | None = ...): ...
def get_my_commands(token, scope: Incomplete | None = ..., language_code: Incomplete | None = ...): ...
def set_my_name(token, name: Incomplete | None = ..., language_code: Incomplete | None = ...): ...
def get_my_name(token, language_code: Incomplete | None = ...): ...
def set_chat_menu_button(token, chat_id: Incomplete | None = ..., menu_button: Incomplete | None = ...): ...
def get_chat_menu_button(token, chat_id: Incomplete | None = ...): ...
def set_my_default_administrator_rights(token, rights: Incomplete | None = ..., for_channels: Incomplete | None = ...): ...
def get_my_default_administrator_rights(token, for_channels: Incomplete | None = ...): ...
def set_my_commands(token, commands, scope: Incomplete | None = ..., language_code: Incomplete | None = ...): ...
def delete_my_commands(token, scope: Incomplete | None = ..., language_code: Incomplete | None = ...): ...
def set_chat_description(token, chat_id, description): ...
def pin_chat_message(token, chat_id, message_id, disable_notification: Incomplete | None = ...): ...
def unpin_chat_message(token, chat_id, message_id): ...
def unpin_all_chat_messages(token, chat_id): ...
def edit_message_text(token, text, chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ..., parse_mode: Incomplete | None = ..., entities: Incomplete | None = ..., disable_web_page_preview: Incomplete | None = ..., reply_markup: Incomplete | None = ...): ...
def edit_message_caption(token, caption, chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ..., parse_mode: Incomplete | None = ..., caption_entities: Incomplete | None = ..., reply_markup: Incomplete | None = ...): ...
def edit_message_media(token, media, chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ...): ...
def edit_message_reply_markup(token, chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ...): ...
def delete_message(token, chat_id, message_id, timeout: Incomplete | None = ...): ...
def send_game(token, chat_id, game_short_name, disable_notification: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def set_game_score(token, user_id, score, force: Incomplete | None = ..., disable_edit_message: Incomplete | None = ..., chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ...): ...
def get_game_high_scores(token, user_id, chat_id: Incomplete | None = ..., message_id: Incomplete | None = ..., inline_message_id: Incomplete | None = ...): ...
def send_invoice(token, chat_id, title, description, invoice_payload, provider_token, currency, prices, start_parameter: Incomplete | None = ..., photo_url: Incomplete | None = ..., photo_size: Incomplete | None = ..., photo_width: Incomplete | None = ..., photo_height: Incomplete | None = ..., need_name: Incomplete | None = ..., need_phone_number: Incomplete | None = ..., need_email: Incomplete | None = ..., need_shipping_address: Incomplete | None = ..., send_phone_number_to_provider: Incomplete | None = ..., send_email_to_provider: Incomplete | None = ..., is_flexible: Incomplete | None = ..., disable_notification: Incomplete | None = ..., reply_to_message_id: Incomplete | None = ..., reply_markup: Incomplete | None = ..., provider_data: Incomplete | None = ..., timeout: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., max_tip_amount: Incomplete | None = ..., suggested_tip_amounts: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def answer_shipping_query(token, shipping_query_id, ok, shipping_options: Incomplete | None = ..., error_message: Incomplete | None = ...): ...
def answer_pre_checkout_query(token, pre_checkout_query_id, ok, error_message: Incomplete | None = ...): ...
def unpin_all_general_forum_topic_messages(token, chat_id): ...
def answer_callback_query(token, callback_query_id, text: Incomplete | None = ..., show_alert: Incomplete | None = ..., url: Incomplete | None = ..., cache_time: Incomplete | None = ...): ...
def answer_inline_query(token, inline_query_id, results, cache_time: Incomplete | None = ..., is_personal: Incomplete | None = ..., next_offset: Incomplete | None = ..., button: Incomplete | None = ...): ...
def get_sticker_set(token, name): ...
def get_custom_emoji_stickers(token, custom_emoji_ids): ...
def set_sticker_keywords(token, sticker, keywords: Incomplete | None = ...): ...
def set_sticker_mask_position(token, sticker, mask_position: Incomplete | None = ...): ...
def upload_sticker_file(token, user_id, sticker, sticker_format): ...
def set_custom_emoji_sticker_set_thumbnail(token, name, custom_emoji_id: Incomplete | None = ...): ...
def set_sticker_set_title(token, name, title): ...
def delete_sticker_set(token, name): ...
def set_sticker_emoji_list(token, sticker, emoji_list): ...
def create_new_sticker_set(token, user_id, name, title, stickers, sticker_format, sticker_type: Incomplete | None = ..., needs_repainting: Incomplete | None = ...): ...
def add_sticker_to_set(token, user_id, name, sticker): ...
def set_sticker_position_in_set(token, sticker, position): ...
def delete_sticker_from_set(token, sticker): ...
def answer_web_app_query(token, web_app_query_id, result: types.InlineQueryResultBase): ...
def create_invoice_link(token, title, description, payload, provider_token, currency, prices, max_tip_amount: Incomplete | None = ..., suggested_tip_amounts: Incomplete | None = ..., provider_data: Incomplete | None = ..., photo_url: Incomplete | None = ..., photo_size: Incomplete | None = ..., photo_width: Incomplete | None = ..., photo_height: Incomplete | None = ..., need_name: Incomplete | None = ..., need_phone_number: Incomplete | None = ..., need_email: Incomplete | None = ..., need_shipping_address: Incomplete | None = ..., send_phone_number_to_provider: Incomplete | None = ..., send_email_to_provider: Incomplete | None = ..., is_flexible: Incomplete | None = ...): ...
def send_poll(token, chat_id, question, options, is_anonymous: Incomplete | None = ..., type: Incomplete | None = ..., allows_multiple_answers: Incomplete | None = ..., correct_option_id: Incomplete | None = ..., explanation: Incomplete | None = ..., explanation_parse_mode: Incomplete | None = ..., open_period: Incomplete | None = ..., close_date: Incomplete | None = ..., is_closed: Incomplete | None = ..., disable_notification: bool = ..., reply_to_message_id: Incomplete | None = ..., allow_sending_without_reply: Incomplete | None = ..., reply_markup: Incomplete | None = ..., timeout: Incomplete | None = ..., explanation_entities: Incomplete | None = ..., protect_content: Incomplete | None = ..., message_thread_id: Incomplete | None = ...): ...
def create_forum_topic(token, chat_id, name, icon_color: Incomplete | None = ..., icon_custom_emoji_id: Incomplete | None = ...): ...
def edit_forum_topic(token, chat_id, message_thread_id, name: Incomplete | None = ..., icon_custom_emoji_id: Incomplete | None = ...): ...
def close_forum_topic(token, chat_id, message_thread_id): ...
def reopen_forum_topic(token, chat_id, message_thread_id): ...
def delete_forum_topic(token, chat_id, message_thread_id): ...
def unpin_all_forum_topic_messages(token, chat_id, message_thread_id): ...
def get_forum_topic_icon_stickers(token): ...
def stop_poll(token, chat_id, message_id, reply_markup: Incomplete | None = ...): ...
def edit_general_forum_topic(token, chat_id, name): ...
def close_general_forum_topic(token, chat_id): ...
def reopen_general_forum_topic(token, chat_id): ...
def hide_general_forum_topic(token, chat_id): ...
def unhide_general_forum_topic(token, chat_id): ...
def convert_input_media(media): ...
def convert_input_media_array(array): ...

class ApiException(Exception):
    function_name: Incomplete
    result: Incomplete
    def __init__(self, msg, function_name, result) -> None: ...

class ApiHTTPException(ApiException):
    def __init__(self, function_name, result) -> None: ...

class ApiInvalidJSONException(ApiException):
    def __init__(self, function_name, result) -> None: ...

class ApiTelegramException(ApiException):
    result_json: Incomplete
    error_code: Incomplete
    description: Incomplete
    def __init__(self, function_name, result, result_json) -> None: ...
