from _typeshed import Incomplete
from redis.asyncio.client import Pipeline as Pipeline, Redis as Redis

def from_url(url, **kwargs): ...

class pipeline:
    p: Incomplete
    def __init__(self, redis_obj: Redis) -> None: ...
    async def __aenter__(self) -> Pipeline: ...
    async def __aexit__(self, exc_type, exc_value, traceback) -> None: ...
