from redis.typing import KeyT as KeyT, KeysT as KeysT
from typing import List, Tuple

def list_or_args(keys: KeysT, args: Tuple[KeyT, ...]) -> List[KeyT]: ...
def nativestr(x): ...
def delist(x): ...
def parse_to_list(response): ...
def parse_list_to_dict(response): ...
def parse_to_dict(response): ...
def random_string(length: int = ...): ...
def quote_string(v): ...
def decode_dict_keys(obj): ...
def stringify_param_value(value): ...
def get_protocol_version(client): ...
