class RedisModuleCommands:
    def json(self, encoder=..., decoder=...): ...
    def ft(self, index_name: str = ...): ...
    def ts(self): ...
    def bf(self): ...
    def cf(self): ...
    def cms(self): ...
    def topk(self): ...
    def tdigest(self): ...
    def graph(self, index_name: str = ...): ...

class AsyncRedisModuleCommands(RedisModuleCommands):
    def ft(self, index_name: str = ...): ...
    def graph(self, index_name: str = ...): ...
