from _typeshed import Incomplete
from sqlalchemy.testing import fixtures

class UnicodeSchemaTest(fixtures.TablesTest):
    __requires__: Incomplete
    __backend__: bool
    @classmethod
    def define_tables(cls, metadata) -> None: ...
    def test_insert(self, connection) -> None: ...
    def test_col_targeting(self, connection) -> None: ...
    def test_reflect(self, connection) -> None: ...
    def test_repr(self) -> None: ...
