from _typeshed import Incomplete
from sqlalchemy.testing import fixtures

class RowCountTest(fixtures.TablesTest):
    __requires__: Incomplete
    __backend__: bool
    @classmethod
    def define_tables(cls, metadata) -> None: ...
    @classmethod
    def insert_data(cls, connection) -> None: ...
    def test_basic(self, connection) -> None: ...
    def test_non_rowcount_scenarios_no_raise(self, connection, statement, close_first) -> None: ...
    def test_update_rowcount1(self, connection) -> None: ...
    def test_update_rowcount2(self, connection) -> None: ...
    def test_update_delete_rowcount_return_defaults(self, connection, implicit_returning, dml) -> None: ...
    def test_raw_sql_rowcount(self, connection) -> None: ...
    def test_text_rowcount(self, connection) -> None: ...
    def test_delete_rowcount(self, connection) -> None: ...
    def test_multi_update_rowcount(self, connection) -> None: ...
    def test_multi_delete_rowcount(self, connection) -> None: ...
