from ..exceptions import ConnectionError as ConnectionError, InvalidResponse as InvalidResponse, ResponseError as ResponseError
from ..typing import EncodableT as EncodableT
from .base import _AsyncRESPBase, _RESPBase
from .socket import SERVER_CLOSED_CONNECTION_ERROR as SERVER_CLOSED_CONNECTION_ERROR
from _typeshed import Incomplete

class _RESP3Parser(_RESPBase):
    push_handler_func: Incomplete
    def __init__(self, socket_read_size) -> None: ...
    def handle_push_response(self, response): ...
    def read_response(self, disable_decoding: bool = ..., push_request: bool = ...): ...
    def set_push_handler(self, push_handler_func) -> None: ...

class _AsyncRESP3Parser(_AsyncRESPBase):
    push_handler_func: Incomplete
    def __init__(self, socket_read_size) -> None: ...
    def handle_push_response(self, response): ...
    async def read_response(self, disable_decoding: bool = ..., push_request: bool = ...): ...
    def set_push_handler(self, push_handler_func) -> None: ...
