import socket
from ..exceptions import ConnectionError as ConnectionError, TimeoutError as TimeoutError
from ..utils import SSL_AVAILABLE as SSL_AVAILABLE
from _typeshed import Incomplete

NONBLOCKING_EXCEPTION_ERROR_NUMBERS: Incomplete
NONBLOCKING_EXCEPTIONS: Incomplete
SERVER_CLOSED_CONNECTION_ERROR: str
SENTINEL: Incomplete
SYM_CRLF: bytes

class SocketBuffer:
    socket_read_size: Incomplete
    socket_timeout: Incomplete
    def __init__(self, socket: socket.socket, socket_read_size: int, socket_timeout: float) -> None: ...
    def unread_bytes(self) -> int: ...
    def can_read(self, timeout: float) -> bool: ...
    def read(self, length: int) -> bytes: ...
    def readline(self) -> bytes: ...
    def get_pos(self) -> int: ...
    def rewind(self, pos: int) -> None: ...
    def purge(self) -> None: ...
    def close(self) -> None: ...
