from _typeshed import Incomplete

class RedisError(Exception): ...
class ConnectionError(RedisError): ...
class TimeoutError(RedisError): ...
class AuthenticationError(ConnectionError): ...
class AuthorizationError(ConnectionError): ...
class BusyLoadingError(ConnectionError): ...
class InvalidResponse(RedisError): ...
class ResponseError(RedisError): ...
class DataError(RedisError): ...
class PubSubError(RedisError): ...
class WatchError(RedisError): ...
class NoScriptError(ResponseError): ...
class OutOfMemoryError(ResponseError): ...
class ExecAbortError(ResponseError): ...
class ReadOnlyError(ResponseError): ...
class NoPermissionError(ResponseError): ...
class ModuleError(ResponseError): ...
class LockError(RedisError, ValueError): ...
class LockNotOwnedError(LockError): ...
class ChildDeadlockedError(Exception): ...
class AuthenticationWrongNumberOfArgsError(ResponseError): ...
class RedisClusterException(Exception): ...
class ClusterError(RedisError): ...

class ClusterDownError(ClusterError, ResponseError):
    args: Incomplete
    message: Incomplete
    def __init__(self, resp) -> None: ...

class AskError(ResponseError):
    args: Incomplete
    message: Incomplete
    slot_id: Incomplete
    node_addr: Incomplete
    def __init__(self, resp) -> None: ...

class TryAgainError(ResponseError):
    def __init__(self, *args, **kwargs) -> None: ...

class ClusterCrossSlotError(ResponseError):
    message: str

class MovedError(AskError): ...
class MasterDownError(ClusterDownError): ...
class SlotNotCoveredError(RedisClusterException): ...
class MaxConnectionsError(ConnectionError): ...
