from _typeshed import Incomplete
from redis.exceptions import AuthorizationError as AuthorizationError, ConnectionError as ConnectionError

def ocsp_staple_verifier(con, ocsp_bytes, expected: Incomplete | None = ...): ...

class OCSPVerifier:
    SOCK: Incomplete
    HOST: Incomplete
    PORT: Incomplete
    CA_CERTS: Incomplete
    def __init__(self, sock, host, port, ca_certs: Incomplete | None = ...) -> None: ...
    def components_from_socket(self): ...
    def components_from_direct_connection(self): ...
    def build_certificate_url(self, server, cert, issuer_cert): ...
    def check_certificate(self, server, cert, issuer_url): ...
    def is_valid(self): ...
