from .. import exc as exc, util as util
from _typeshed import Incomplete
from typing import Any, Callable

CANCEL: Incomplete
NO_RETVAL: Incomplete

def listen(target: Any, identifier: str, fn: Callable[..., Any], *args: Any, **kw: Any) -> None: ...
def listens_for(target: Any, identifier: str, *args: Any, **kw: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def remove(target: Any, identifier: str, fn: Callable[..., Any]) -> None: ...
def contains(target: Any, identifier: str, fn: Callable[..., Any]) -> bool: ...
